service:
  name: aws-nodejs-typescript

custom:
  serverless-offline:
    port: 4000
  apigwBinary:
    types:
      - 'image/jpeg'
      - 'image/png'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-apigw-binary
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  # TODO: lock this down to only needed perms
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ]]}
        - "arn:aws:s3:::thumbnailerthumbs/*"

functions:
  resize:
    handler: handler.resize
    events:
      - http:
          method: get
          path: /resize/{imageUrl+}
  meta:
    handler: handler.meta
    events:
      - http:
          method: get
          path: /meta/{imageUrl+}

resources:
  Resources:
    thumbnailerBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: thumbnailerthumbs
    thumbnailerApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: dev-aws-nodejs-typescript
        BinaryMediaTypes:
          - "application~1octet-stream"
